tf_version:
- 2.3
cudnn:
- 7.6
cuda_compiler_version:
- None
float_prec:
- low
- high
channel_sources:
- deepmodeling,defaults
channel_targets:
- deepmodeling main
cuda_compiler_version:  
- None
- 9.2
- 10.0  
- 10.1
c_compiler_version:
- 5.4
cxx_compiler_version:
- 5.4
