tf_version:
- 2.0.0
cudnn:
- 7.6
cuda_compiler_version:
- None
float_prec:
- low
- high
channel_sources:
- deepmodeling,defaults
channel_targets:
- deepmodeling main
cuda_compiler_version:  
- None
- 10.0  
c_compiler_version:
- 5.4
cxx_compiler_version:
- 5.4
