float_prec:
- low
- high
c_compiler_version:
- 8
cxx_compiler_version:
- 8
channel_sources:
- deepmodeling/label/dev,deepmodeling,defaults,nvidia
channel_targets:
- deepmodeling dev
cuda_compiler_version:  
- None
- 9.2
- 10.0
- 10.1  
#- 10.2
- 11.0
- 11.1
docker_image:
- quay.io/condaforge/linux-anvil-cos7-x86_64
- quay.io/condaforge/linux-anvil-cos7-cuda:9.2
- quay.io/condaforge/linux-anvil-cos7-cuda:10.0
- quay.io/condaforge/linux-anvil-cos7-cuda:10.1
#- quay.io/condaforge/linux-anvil-cuda:10.2
- quay.io/condaforge/linux-anvil-cuda:11.0
- quay.io/condaforge/linux-anvil-cuda:11.1
cudnn:
- None
- 7
- 7
- 7
#- 8
- 8
- 8
cdt_name:
- cos7
- cos7
- cos7
- cos7
#- cos7
- cos7
- cos7
zip_keys:
  - - cudnn
    - cuda_compiler_version
    - docker_image
    - cdt_name
