dp_variant:
- cpu
- gpu
tf_version:
- 2.0.0
cudatoolkit:
- 10.0
cudnn:
- 7.6
docker_image:
- condaforge/linux-anvil-comp7
- condaforge/linux-anvil-cuda:10.0
zip_keys:
- dp_variant
- docker_image
float_prec:
- low
- high
channel_sources:
- deepmodeling,defaults
channel_targets:
- deepmodeling main
