{% set name = "libdeepmd" %}
{% set version = "2.0.0.b4" %}
{% if cuda_compiler_version == "None" %}
{% set dp_variant = "cpu" %}
{% else %}
{% set dp_variant = "gpu" %}
{% endif %}

{% set tf_version = "2.5" %}

{% set tf = "{} {}".format(tf_version, dp_variant) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source: 
  git_url: https://github.com/deepmodeling/deepmd-kit
  git_rev: v{{ version }}

build:
  number: 0
  string: "{{ PKG_BUILDNUM }}_cuda{{ cuda_compiler_version }}_{{ dp_variant }}"
  run_exports:
    - libdeepmd {{ version }} *{{ dp_variant }}
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - git
  host:
    - cudatoolkit {{ cuda_compiler_version }}*  # [cuda_compiler_version != 'None']
    - cudnn {{ cudnn }}*  # [cuda_compiler_version != 'None']
    - libtensorflow_cc {{ tf }}*
    - intel-openmp  # [linux64]
  run:
    - libtensorflow_cc {{ tf }}*
    - {{ pin_compatible('cudatoolkit', max_pin='x.x') }}  # [cuda_compiler_version != 'None']
    - {{ pin_compatible('cudnn') }}  # [cuda_compiler_version != 'None']
    - intel-openmp  # [linux64]
  run_constrained:
    - lammps-dp >=2.0.0.b3

test:
  commands:
    - ldd $PREFIX/bin/dp_ipi

about:
  home: https://github.com/deepmodeling/deepmd-kit
  license: LGPL-3.0
  license_family: LGPL
  license_file: LICENSE
  summary: 'A deep learning package for many-body potential energy representation and molecular dynamics'
  doc_url: https://github.com/deepmodeling/deepmd-kit
  dev_url: https://github.com/deepmodeling/deepmd-kit

extra:
  recipe-maintainers:
    - njzjz
