{% set name = "libdeepmd" %}
{% set version = "1.1.2" %}
{% set cudatoolkit = cuda_compiler_version %}
{% if cuda_compiler_version == "None" %}
{% set dp_variant = "cpu" %}
{% else %}
{% set dp_variant = "gpu" %}
{% endif %}
{% set tf = "{} {}".format(tf_version, dp_variant) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source: 
  git_url: https://github.com/deepmodeling/deepmd-kit
  git_rev: v1.1.2

build:
  number: 1
  string: "{{ PKG_BUILDNUM }}_{{ dp_variant }}"  # [float_prec == 'high']
  string: "{{ PKG_BUILDNUM }}_{{ dp_variant }}_{{float_prec}}"  # [float_prec != 'high']
  run_exports:
    - libdeepmd {{ version }} *{{ dp_variant }}  # [float_prec == 'high']
    - libdeepmd {{ version }} *{{ dp_variant }}_{{ float_prec }}  # [float_prec != 'high']
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - git
  host:
    - cudatoolkit {{ cudatoolkit }}*  # [cuda_compiler_version != 'None']
    - cudnn {{ cudnn }}*  # [cuda_compiler_version != 'None']
    - libtensorflow_cc {{ tf }}*
  run:
    - libtensorflow_cc {{ tf }}*
    - {{ pin_compatible('cudatoolkit', max_pin='x.x') }}  # [cuda_compiler_version != 'None']
    - {{ pin_compatible('cudnn') }}  # [cuda_compiler_version != 'None']

about:
  home: https://github.com/deepmodeling/deepmd-kit
  license: LGPL-3.0
  license_family: LGPL
  license_file: LICENSE
  summary: 'A deep learning package for many-body potential energy representation and molecular dynamics'
  doc_url: https://github.com/deepmodeling/deepmd-kit
  dev_url: https://github.com/deepmodeling/deepmd-kit

extra:
  recipe-maintainers:
    - njzjz
