{% set name = "libdeepmd" %}
{% set version = "2.2.4" %}
{% if cuda_compiler_version == "None" %}
{% set dp_variant = "cpu" %}
{% set tf_variant = "cpu" %}
{% else %}
{% set dp_variant = "gpu" %}
{% set tf_variant = "cuda" %}
{% endif %}

{% set tf_version = "2.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source: 
  git_url: https://github.com/deepmodeling/deepmd-kit
  git_rev: v{{ version }}
  patches:
    - comment_host_compiler.patch  # [cuda_compiler_version == '10.2']

build:
  number: 0
  string: "{{ PKG_BUILDNUM }}_cuda{{ cuda_compiler_version }}_{{ dp_variant }}"
  run_exports:
    - libdeepmd
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}  # [cuda_compiler_version != 'None']
    - cmake >=3.23
    - make
    - git
  host:
    - libtensorflow_cc {{ tf_version }}.* {{ tf_variant }}*
    - mpich
  run:
    - libtensorflow_cc {{ tf_version }}.* {{ tf_variant }}*
    - {{ pin_compatible('mpich') }}
    - __cuda  # [cuda_compiler_version != 'None']
    - cudnn  # [cuda_compiler_version != 'None']
  run_constrained:
    - lammps 20230802.0
    # deprecated lammps
    - lammps-dp 99999999

test:
  requires:
    - deepmd-kit  # [cuda_compiler_version == 'None']
    - lammps 20230802.0  # [cuda_compiler_version == 'None']
  files:
    - water_se_a.json  # [cuda_compiler_version == 'None']
    - water.lmp  # [cuda_compiler_version == 'None']
    - in.lammps  # [cuda_compiler_version == 'None']
  source_files:
    - examples/water/data  # [cuda_compiler_version == 'None']
  commands:
    - ldd $PREFIX/bin/dp_ipi
    - mv examples/water/data/data_0 ./data  # [cuda_compiler_version == 'None']
    - dp train water_se_a.json  # [cuda_compiler_version == 'None']
    - dp freeze -o frozen_model.pb  # [cuda_compiler_version == 'None']
    - mpiexec -n 1 lmp -in in.lammps  # [cuda_compiler_version == 'None']


about:
  home: https://github.com/deepmodeling/deepmd-kit
  license: LGPL-3.0
  license_family: LGPL
  license_file: LICENSE
  summary: 'A deep learning package for many-body potential energy representation and molecular dynamics'
  doc_url: https://github.com/deepmodeling/deepmd-kit
  dev_url: https://github.com/deepmodeling/deepmd-kit

extra:
  recipe-maintainers:
    - njzjz
