# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

jobs:
- job: linux
  pool:
    vmImage: ubuntu-latest
  strategy:
    matrix:
      linux_64_cuda_compiler_version10.1cudnn7:
        CONFIG: linux_64_cuda_compiler_version10.1cudnn7
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-cuda:10.1
      linux_64_cuda_compiler_version11.3cudnn8:
        CONFIG: linux_64_cuda_compiler_version11.3cudnn8
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: ghcr.io/deepmd-kit-recipes/linux-anvil-cuda:11.3
      linux_64_cuda_compiler_versionNonecudnnundefined:
        CONFIG: linux_64_cuda_compiler_versionNonecudnnundefined
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-cos7-x86_64
      linux_ppc64le_cuda_compiler_version10.2cudnn8:
        CONFIG: linux_ppc64le_cuda_compiler_version10.2cudnn8
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-ppc64le
      linux_ppc64le_cuda_compiler_versionNonecudnnundefined:
        CONFIG: linux_ppc64le_cuda_compiler_versionNonecudnnundefined
        UPLOAD_PACKAGES: 'True'
        DOCKER_IMAGE: quay.io/condaforge/linux-anvil-ppc64le
  timeoutInMinutes: 360

  steps:
  - script: |
         rm -rf /opt/ghc
         df -h
    displayName: Manage disk space

  # configure qemu binfmt-misc running.  This allows us to run docker containers
  # embedded qemu-static
  - script: |
      docker run --rm --privileged multiarch/qemu-user-static:register --reset --credential yes
      ls /proc/sys/fs/binfmt_misc/
    condition: not(startsWith(variables['CONFIG'], 'linux_64'))
    displayName: Configure binfmt_misc

  - script: |
        export CI=azure
        export GIT_BRANCH=$BUILD_SOURCEBRANCHNAME
        export FEEDSTOCK_NAME=$(basename ${BUILD_REPOSITORY_NAME})
        .scripts/run_docker_build.sh
    displayName: Run docker build
    env:
      BINSTAR_TOKEN: $(BINSTAR_TOKEN)